### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by briochemc**
Set the language in the code blocks to allow for GitHub's syntax highlighting, which is nicer on the eye.

### CODE REVIEW

**Review by haanwinckel — APPROVED** [review]
Thanks!

**Comment by briochemc** [comment]
Just a side question if you don't mind: How does it compare to packages like [ModelParameters.jl](https://github.com/rafaqz/ModelParameters.jl) or [SciMLStructures.jl](https://github.com/SciML/SciMLStructures.jl)?

**Comment by haanwinckel** [comment]
Sure, thanks for asking! My package allows for imposing constraints on
vector-valued parameters, such as having the first element always
normalized to zero or one, having all elements add up to one, or being
ordered (which also works for matrix-valued parameters). Besides, it
enforces that constraints/normalizations imposed on parameter names are
shared across all structs with fields with the same name. Whether that's
desired or not depends on the application---it's useful for my models.

To be honest, I did not know about these other packages before, but I do
not think they do what I mentioned above. I am not sure they handle
vector-valued or matrix-valued parameters at all.

Daniel Haanwinckel
+1 510 646 6971

**Comment by briochemc** [comment]
I think ModelParameters doesn't handle arrays but it does have all kinds of similar traits, while SciMLStructures can handle arrays (and nested parameters) but doesn't have the other features, although I may be wrong (these aren't my packages).

**Pull request merged**
